export enum AccountsEnum {
    LOAD_ACCOUNTS = "LOAD_ACCOUNTS",
    LOAD_ACCOUNTS_FAILURE = "LOAD_ACCOUNTS_FAILURE",
    LOAD_ACCOUNTS_SUCCESS = "LOAD_ACCOUNTS_SUCCESS",
    CHANGE_ACCOUNT_TITLE = "CHANGE_ACCOUNT_TITLE",
    ADD_ACCOUNT = "ADD_ACCOUNT",
    REMOVE_EXTERNAL_ACCOUNT = "REMOVE_EXTERNAL_ACCOUNT",
}
