image: mhart/alpine-node:14

stages:
  - lint
  - test
  - build

lint test:
  stage: lint
  script:
    - npm install --progress=false
    - npm run lint

unit test:
  stage: test
  script:
    - npm install --progress=false
    - npm run test

build site:
  stage: build
  script:
    - npm install --progress=false
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - build
